/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tddbe.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testMultiplication() {
        Dollar five = new Dollar(5);
        Dollar product = five.times(2);
        assertEquals(10, product.amount);
        product = product.times(2);
        assertEquals(20, product.amount);
    }
}
